# Generated by Django 3.2.19 on 2023-10-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionsDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='value',
            field=models.TextField(),
        ),
    ]
